name: End To End Tests

on: push

jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}
    env:
      PORT: ${{ vars.PORT }}
      APP_URL: ${{ vars.APP_URL }}
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Npm Packages Client
        run: npm i
        working-directory: client

      - name: Install Npm Packages API
        run: npm i
        working-directory: server
    
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          working-directory: client
          start: |
            npm run dev --prefix ../server
            npm run dev
      
      - name: Upload ScreenShots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots
          if-no-files-found: ignore

      - name: Run Coverage Report
        run: npx nyc report --reporter=text-summary
        working-directory: client # or server depending on where nyc is set up

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/*.json
          directory: ./coverage
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true