name: End To End Tests

on: push

jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}
    env:
      PORT: ${{ vars.PORT }}
      APP_URL: ${{ vars.APP_URL }}
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Npm Packages Client
        run: npm i
        working-directory: client

      - name: Install Npm Packages API
        run: npm i
        working-directory: server
    
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          working-directory: client
          start: |
            npm run dev --prefix ../server
            npm run dev